### ISSUE TITLE
Problem for running the ddi

### ISSUE THREAD

**Issue by Juanhui28** [melifluos/subgraph-sketching#2] opened 2023-04-06 20:53 UTC
Dear authors,

Thanks for providing the source code of the ELPH/BUDDY. When I tried to run the ddi following the command  `python runners/run.py --dataset ogbl-ddi --K 20 --train_node_embedding --propagate_embeddings --epochs 120 --num_negs 6 --model BUDDY `, I got the error: `AttributeError: 'BUDDY' object has no attribute 'sign_embedding'`.  Could you please help?

Best,
Juanhui

**Comment by Juanhui28** [comment] 2023-04-14 05:16
@melifluos @shir994 
I forgot to add mentions, if you know anything about this, please let me know.

**Comment by melifluos** [comment] 2023-04-16 20:49
@Juanhui28 thanks for brining this to our attention. I will look into it and get back to you shortly, Ben.

**Comment by melifluos** [comment] 2023-04-19 14:29
@Juanhui28 this has been resolved in https://github.com/melifluos/subgraph-sketching/pull/4
for ogbl-ddi --use_feature 0 and sign_k 2 have been added to defaults. We apologise for the error.

**Comment by Juanhui28** [comment] 2023-04-20 04:57
It works. Thank you so much! @melifluos

**Comment by voladorlu** [comment] 2023-04-23 03:00
@melifluos I successfully run the code on ogbl-ppi data with the suggested command ""python runners/run.py --dataset ogbl-ddi --train_node_embedding --propagate_embeddings --epochs 150 --hidden_channels 256 --lr 0.0015 --num_negs 6 --use_feature 0 --sign_k 2 --batch_size 131072 --model BUDDY
"". It looks like that the updated code gets too much better result (Hit@20: 93.5%) than the one (Hit@20:78.5) shown in the paper. It's a little strange to see such phenomenon. Do you have any comments on this?

**Comment by melifluos** [comment] 2023-04-24 18:58
@voladorlu is that just one run or an average? 

That does seem a bit too good though. Due to events at Twitter we lost access to the original code and hyperparameters and so this code is our best effort to reproduce what we did and not the same codebase

**Comment by melifluos** [comment] 2023-04-24 20:08
Actually @voladorlu, now I think about it, it's probably doing HR@100. set --K 20 to be sure. I'll also update this in the running instructions.

**Comment by voladorlu** [comment] 2023-04-25 06:46
@melifluos Yes, you are right. It looks well after set --K 20. Thanks so much for fixing the problem.

**Closed as completed** 2023-04-25 22:02 UTC
